title = "BridgeNet2"
gitRepoUrl = "https://github.com/ffrostflame/bridgenet2/"

changelog = true

[docusaurus]
projectName = "BridgeNet2"
tagline = "Blazing fast & opinionated networking library designed to reduce bandwidth"
favicon = "favicon.png"

[navbar.logo]
alt = "BridgeNet2"
src = "logo.png"

[footer]
style = "dark"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Cuts the header from RemoteEvents"
description = "BridgeNet2 cuts down successive remote event call size from 9 bytes to 2 bytes"

[[home.features]]
title = "Feature 1"
description = "This is a feature"