title = "BridgeNet2"
gitRepoUrl = "https://github.com/ffrostflame/bridgenet2/"

changelog = true

[docusaurus]
projectName = "BridgeNet2"
tagline = "Easy to use, optimized, and full of useful functionality."
favicon = "favicon.png"

[navbar.logo]
alt = "BridgeNet2"
src = "logo.png"

[footer]
style = "dark"

[home]
enabled = true
includeReadme = false